name : TestRun

on : workflow_dispatch

jobs : 
  job1:
    name: First Job
    runs-on: ubuntu-latest 
    steps:
      - name: First Step
        uses: actions/checkout@v2
      - name: Second Step
        run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest 
    steps:
      - name: First Step
        uses: actions/checkout@v2
      - name: Second Job
        run: "Get-ChildItem env: | Sort-Object Name"
      
    
